In [2]:
from scipy.signal import convolve
import numpy as np

In [5]:
I = np.arange(25)
I = I.reshape(5,5)

In [6]:
binomial_kernel = np.array([[1,2,1]])
dx_filter = np.array([[1/2,0,-1/2]])

In [19]:
convolve(convolve(I,binomial_kernel,mode='same'), dx_filter, mode='same')

array([[  2. ,   3.5,   4. ,   1.5,  -6. ],
       [ 12. ,   6. ,   4. ,  -1. , -16. ],
       [ 22. ,   8.5,   4. ,  -3.5, -26. ],
       [ 32. ,  11. ,   4. ,  -6. , -36. ],
       [ 42. ,  13.5,   4. ,  -8.5, -46. ]])

In [20]:
convolve(I, convolve(binomial_kernel, dx_filter,mode='same'), mode='same')

array([[  1.,   2.,   2.,   2.,  -3.],
       [  6.,   2.,   2.,   2.,  -8.],
       [ 11.,   2.,   2.,   2., -13.],
       [ 16.,   2.,   2.,   2., -18.],
       [ 21.,   2.,   2.,   2., -23.]])

In [34]:
shift = np.array([[0,1,2,1]])

In [35]:
convolve(I,shift,mode='valid')

array([[ 4,  8],
       [24, 28],
       [44, 48],
       [64, 68],
       [84, 88]])

In [36]:
convolve(I,binomial_kernel,mode='valid')

array([[ 4,  8, 12],
       [24, 28, 32],
       [44, 48, 52],
       [64, 68, 72],
       [84, 88, 92]])

In [37]:
m = np.array([[30,10,10],[12,45,13],[17,10,33]])

In [38]:
(30+45+33)/np.sum(m)

0.6

In [39]:
1-0.31271-0.32902

0.35827

In [40]:
P = np.array([[900,0,600,0],[0,900,400,0],[0,0,1,0]])
P

array([[900,   0, 600,   0],
       [  0, 900, 400,   0],
       [  0,   0,   1,   0]])

In [41]:
X = np.array([[1],[2],[3],[4]])

In [42]:
P.dot(X)

array([[2700],
       [3000],
       [   3]])

In [56]:
Rt = np.array([[0,-1,0,1],[1,0,0,2],[0,0,1,3]])
Rt

array([[ 0, -1,  0,  1],
       [ 1,  0,  0,  2],
       [ 0,  0,  1,  3]])

In [48]:
c = np.array([[0],[0],[1]])
c

array([[0],
       [0],
       [1]])

In [57]:
np.linalg.inv(Rt.T.dot(Rt)).dot(Rt.T).dot(c)

LinAlgError: Singular matrix